name:                fp-lang
version:             0.1.0.0
github:              "githubuser/fp-lang"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/fp-lang#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - megaparsec
  - parser-combinators

default-extensions: 
  - BlockArguments

library:
  source-dirs: src

executables:
  fp-lang:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-lang

tests:
  fp-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-lang
    - hspec
    - hspec-discover
    - hspec-megaparsec
